jobs:
- job: Sonar_Cloud_Analysis
  displayName: 'Running Sonar Cloud Analysis'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
  
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'Sonar_CTSE'
      organization: 'pasindu-madhuwantha'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'Pasindu-Madhuwantha_E-Commerce-Deployment'
      cliProjectName: 'E-Commerce-Deployment'
      cliSources: '.'

  - task: SonarCloudAnalyze@1
    inputs:
      jdkVersion: 'JAVA_HOME_17_X64'

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'

- job: Save_Repo_As_Artifact
  displayName: 'Save repository as artifact'
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: Sonar_Cloud_Analysis
  steps:
  - checkout: self

  # Download the config.env file from Azure DevOps library
  - task: DownloadSecureFile@1
    displayName: 'Download config.env file'
    inputs:
      secureFile: 'config.env'  # Name of the secure file in the Azure DevOps library

  # Copy all files and folders to artifact staging directory
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  # Copy config.env file to the backend/config directory in artifact
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(DownloadSecureFile.secureFilePath)'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/backend/config'

  # Ensure the config.env file is there in the artifact directory
  - script: ls $(Build.ArtifactStagingDirectory)/backend/config
    displayName: 'Check if config.env is in the artifact directory'

  - task: PublishBuildArtifacts@1    
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
