jobs:
- job: Save_Repo_As_Artifact
  displayName: 'Save repository as artifact'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
  - task: CopyFiles@2
    inputs:
     targetFolder: '$(Build.ArtifactStagingDirectory)'    

  - task: PublishBuildArtifacts@1    
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'

