trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerImageName: 'mydockerimage'  # Change this to match your Docker image name

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

    - script: |
        docker save -o $(Build.ArtifactStagingDirectory)/$(dockerImageName).tar $(dockerImageName):$(tag)
      displayName: 'Save Docker image as tarball'

    - task: PublishBuildArtifacts@1    
      displayName: 'Publish Artifact: dockerimage'
      inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'dockerimage'
