trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        command: 'build'
        containerRegistry: 'docker777'
        repository: 'pasindu1952/ecommerce'
        Dockerfile: '**/Dockerfile'
        tags: |
            $(tag)


