trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build
      inputs:
        containerRegistry: 'docker777'
        repository: 'pasindu1952/ecommerce:47'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/**/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          $(tag)
          $(Build.BuildNumber)
          $(Build.BuildId)
    - task: Bash@3
      displayName: Save Docker Image
      inputs:
        targetType: 'inline'
        script: |
          docker save -o $(Build.ArtifactStagingDirectory)/image.tar image:$(Build.BuildNumber)
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/image.tar'
        artifact: 'my-artifact'
        publishLocation: 'pipeline'
